[project]
name = "password-hash"
readme = "README.md"
description = "A secure and modern library for hashing passwords."
version = "1.1.0"
requires-python = ">=3.14"
authors = [{name = "Masahiro Koti", email="workspace2110@gmail.com"}]
license = {text = "MIT"}
dependencies = [
    "passlib>=1.7.4",
    "password-strength>=0.0.3.post2",
]

[project.optional-dependencies]
dev = [
    "flake8>=7.3.0",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
